org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.177
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
yacl_version=3.8.1+1.21.1-neoforge
mod_id=brutal_respawn
mod_name=Brutal Respawn
mod_license=MIT
mod_version=1.1
mod_group_id=dev.invalid
mod_authors=vlad0-0
mod_description=A simple mod that makes the resurrection mechanics a little more challenging. This mod can be configured.
